version: '3.8'
services:
  db:
    image: israelaze/mysql-loja
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1905
      MYSQL_USER: docker
      MYSQL_DATABASE: loja
    ports:
      - "3308:3306"
    networks:
      - loja-network
  loja:
    image: israelaze/loja
    restart: always
    build: ./Suporte Docker 
    working_dir: /Suporte Docker
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./Suporte Docker:/Suporte Docker
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - loja-network
networks:
    loja-network:
        driver: bridge